project:
  type: website

website:
  title: "Group15"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: proposal.qmd
        text: Project Overview
      - href: proposal.qmd
        text: User Guide
      - href: proposal.qmd
        text: Application
      - href: proposal.qmd
        text: Poster
      - href: proposal.qmd
        text: Proposal
      - href: about.qmd
        text: About Us
      

format:
  html:
    theme: solar
    css: styles.css
    toc: true

editor: visual

